studybud/simple/urls.py
from .views import login, signup, change_password, reset_password, logout,reset, delete
from django.urls import path

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
    path('change-password/', change_password, name='change_password'),
    path('reset-password/', reset_password, name='reset_password'),
    path('reset-password/<Token>/', reset, name='reset'),
    path('delete/', delete, name='delete')
]

studybud/studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, add_questions, get_form, delete, edit_question, practice, check_answer, report
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'), # type: ignore
    path('add-question/<quiz_id>', add_questions, name='add_questions'),
    path('get-form/<what_form>', get_form, name='get-form'),
    path('edit-question/<ques_id>', edit_question, name='edit_questions'),
    path('practice/<quiz_id>', practice, name='practice'),
    path('check-answers/', check_answer, name='check'),
    path('report/<quiz_id>', report, name='report'), # type: ignore
    path('delete/<type>/<id>', delete, name='delete'), # type: ignore
    path('auth/', include('simple.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studybud/studybud/models.py
from django.db import models
from simple.models import UserModels




class Quiz(models.Model):
    user = models.ForeignKey(UserModels, on_delete=models.CASCADE, default=1) # type: ignore
    quiz_id = models.CharField(unique=True, primary_key=True,max_length=7, editable=False)
    quiz_name = models.CharField(max_length=255, unique=True)
    date_created = models.DateField(auto_now_add=True, editable=False)

class Questions(models.Model):
    quiz_id = models.ForeignKey(Quiz, editable=False, on_delete=models.CASCADE)
    ques_id = models.CharField(unique=True,max_length=7, primary_key=True, editable=False)
    ques = models.CharField(max_length=1000)
    ques_image = models.ImageField(default=None,upload_to='media/question_images')
    ques_date = models.DateField(auto_now_add=True, editable=False)

class Answers(models.Model):
    quiz_id = models.ForeignKey(Quiz, editable=False, on_delete=models.CASCADE)
    ques_id = models.ForeignKey(Questions, editable=False, on_delete=models.CASCADE)
    ans_id = models.CharField(unique=True, primary_key=True,editable=False, max_length=7)
    ans = models.CharField(max_length=1000)
    ans_image = models.ImageField(default=None, upload_to='uploads/answer_images')
    ans_correct = models.BooleanField(default=False)

class Report(models.Model):
    user = models.ForeignKey(UserModels, on_delete=models.CASCADE)
    quiz_id = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.CharField(max_length=1000000)
    wrong = models.CharField(max_length=1000000000000000000)
    correct = models.CharField(max_length=1000000000000000000)
    wrong_len = models.IntegerField()
    correct_len = models.IntegerField()
    time = models.DateTimeField(auto_now_add=True)

studybud/studybud/forms.py
from django import forms
from django.forms import Field

class quiz(forms.Form):
    quiz_name = forms.CharField(label='Name of Test: ', widget=forms.TextInput(attrs={'placeholder': 'Enter the name you want the quiz to have ..'}))

class ques(forms.Form):
    question = forms.CharField(label='Question :', widget=forms.Textarea(attrs={'rows':'4', 'placeholder':'  Add a question here '}))
    ques_image = forms.ImageField(label='Add image')

class ques_no_image(ques):
    ques_image = None

class ans(forms.Form):
    answer = forms.CharField(label='Answer: ')
    answer_with_image = forms.CharField(label='Answer: ')
    ans_img = forms.ImageField(label='Add Image (Answer): ')

class ans_text(ans):
    ans_img = None
    answer_with_image = None

class ans_image(ans):
    answer = None
    answer_with_image = None

class ans_img_text(ans):
    answer = None

class correct_ans(forms.Form):
    correct_answer = forms.CharField(label='Correct Answer')
    correct_img = forms.ImageField(label='Add Image(correct answer)')

class correct_ans_text(correct_ans):
    correct_img = None
    
class correct_ans_image(correct_ans):
    correct_answer = None

studybud/studybud/views.py
from django.shortcuts import render, HttpResponse, redirect
from simple.models import UserModels
from .forms import quiz, ques, ques_no_image, ans_text, correct_ans_text, ans_img_text, ans_image, correct_ans_image, correct_ans, ans
from .models import Quiz, Questions, Answers, Report
from django.urls import reverse
from .deleteimg import delete_image
from itertools import zip_longest
from django.template.loader import render_to_string
from simple.views import login_required, generate_username


def id_gen(number=7):
    id = generate_username(number)
    return id

def validate_input(post_info):
    #  use the form to validate input
    return  ques_no_image(post_info).is_valid() and ans_text(post_info).is_valid() and correct_ans_text(post_info).is_valid() or ques(post_info).is_valid() or ans(post_info).is_valid() or correct_ans(post_info).is_valid() or ans_img_text(post_info) or correct_ans_image(post_info).is_valid() or ans_image(post_info).is_valid()



@login_required
def home(request,  user=None,*args):

    quiz_form  = quiz()
    quizzes = Quiz.objects.filter(user=user).all()
    

    if request.method == 'POST':
        valid = quiz(request.POST).is_valid()
        if valid:
            quiz_id = id_gen()
            quiz_name = request.POST['quiz_name']
            try:
                
                Quiz.objects.create(user=user, quiz_id=quiz_id, quiz_name=quiz_name).save()
                
                return render(request, 'test_created.html', {'quiz_name':quiz_name,'quiz_id':quiz_id})
            except Exception as e:
                error = e.args[0]
                # during developments i found only two errors all about unique constraints this is what i use to solve them, if quiz_id i generate a new one and if it's a quiz_name a random string is added to it
                if error ==  'UNIQUE constraint failed: studybud_quiz.quiz_id':
                    quiz_id = id_gen()
                    Quiz.objects.create(user=user, quiz_id=quiz_id, quiz_name=quiz_name).save()
                    return render(request, 'test_created.html', {'quiz_name':quiz_name,'quiz_id':quiz_id})

                if error == 'UNIQUE constraint failed: studybud_quiz.quiz_name':
                    quiz_name = quiz_name + id_gen(3)
                    Quiz.objects.create(user=user, quiz_id=quiz_id, quiz_name=quiz_name).save()
                    return render(request, 'test_created.html', {'quiz_name':quiz_name,'quiz_id':quiz_id})
            return 
    return render(request, 'home.html', {'quiz_form':quiz_form, 'quizes': quizzes})

@login_required
def add_questions(request, user=None,*args, **kwargs):
    quiz_id = kwargs.get('quiz_id')
    check_exist = Quiz.objects.filter(quiz_id=quiz_id,user=user).exists()

    if not check_exist:
        return HttpResponse(f'You have to create a test first at <a href="{request.build_absolute_uri(reverse('home'))}">This Link</a>')
    
    question = ques_no_image()
    answer = ans_text()
    correct_answer = correct_ans_text()
    questions = Questions.objects.filter(quiz_id=quiz_id).select_related().all()
    
    if request.method == 'POST':
        post_info = request.POST
        images = request.FILES
        anss = post_info.getlist('answer')
        anss_with_image = post_info.getlist('answer_with_image')
        correct_anss = post_info.get('correct_answer')
        join_answers = anss + anss_with_image

        # validate the forms before it start to create the question and answers
        if validate_input(post_info):
            
            if correct_anss not in join_answers:
                ques_id = id_gen()
                quess = str(post_info.get('question'))
                ques_image = images.get('ques_image')
                quiz_inst = Quiz(quiz_id=quiz_id)
                ques_inst = Questions(ques_id=ques_id)
                
                answer_image = images.getlist('ans_img')

                correct_ans_img = images.get('correct_img')
                
                # Create answers with images
                if answer_image:
                    if len(anss_with_image) == len(answer_image):
                        Questions.objects.create(quiz_id=quiz_inst, ques_id=ques_id,ques=quess, ques_image=ques_image).save()
                        for anss_,image_ in list(zip(anss_with_image, answer_image)):
                            ans_id = id_gen()
                            Answers.objects.create(ans_id=ans_id, quiz_id=quiz_inst, ques_id=ques_inst,ans=anss_,ans_image=image_).save()
                    else:
                        return HttpResponse('Check the form images and try again')
                else:
                    # Create question
                    Questions.objects.create(quiz_id=quiz_inst, ques_id=ques_id,ques=quess, ques_image=ques_image).save()

                # Create answers
                for answer in anss:
                    ans_id = id_gen()
                    Answers.objects.create(ans_id=ans_id, quiz_id=quiz_inst, ques_id=ques_inst,ans=answer,ans_image=None).save()

                # Add Correct answer 
                ans_id = id_gen()
                Answers.objects.create(ans_id=ans_id, quiz_id=quiz_inst, ques_id=ques_inst, ans=correct_anss,ans_image=correct_ans_img, ans_correct=True).save()

                return render(request, 'question.html', {'ques_id':ques_id, 'quess':quess})
            else:
                return HttpResponse('Correct answer is in answers')
        else:
            return HttpResponse('Try checking your input and try again or the file size of your image')
    context = {
        'question': question,
        'quiz_id': quiz_id,
        'answer': answer,
        'correct': correct_answer,
        'questions': questions,
        'can_practice': True,
        'quiz_id': quiz_id,
    }
    return render(request, 'add_ques.html', context)



@login_required
def edit_question(request, user=None,*args, **kwargs):
    ques_id = kwargs.get('ques_id')
    
    ques_query = Questions.objects.select_related().filter(ques_id=ques_id)
    if request.method == 'POST':
        post_info = request.POST
        images = request.FILES
        if validate_input(post_info):
            quiz_id=post_info.get('quiz_id')
            # edit quetions
            ques_edit = str(post_info.get('question')).strip()
            ques_edit_image = images.get('image')
            ques_id = post_info.get('ques_id')

            # edit correct answer
            correct_ans_edit = post_info.get('correct_answer')
            correct_ans_id = post_info.get('correct_ans_id')
            
            # edit answers
            ans_edit= post_info.getlist('answer')

            if correct_ans_edit in ans_edit:
                return HttpResponse('Correct answer is in answers')
            if ques_edit_image:
                Questions.objects.filter(ques_id=ques_id).update(ques=ques_edit, ques_image=ques_edit_image)

            Questions.objects.filter(ques_id=ques_id).update(ques=ques_edit)
            answers = list(zip_longest(post_info.getlist('ids'), ans_edit, fillvalue=None))
            quiz_inst = Quiz(quiz_id=quiz_id)
            ques_inst = Questions(ques_id=ques_id)
            for id,answer_edit in answers:
                # update_or_create was causing integrity errors so i used this instead
                id = id
                if id is None:

                    Answers.objects.create(ans_id=id_gen(),quiz_id=quiz_inst,ques_id=ques_inst,ans=answer_edit,ans_image=None).save()
                else:
                    Answers.objects.filter(ans_id=id).update(ans=answer_edit)
            if correct_ans_id:
                Answers.objects.filter(ans_id=id).update(ans=correct_ans_edit)
            
            return HttpResponse('Update Done')
        return HttpResponse('Error check your inputs')
    if not ques_query:
        return redirect('/')
    quiz_id = ques_query.values()[0].get('quiz_id_id')
    
    context = {
        'ques':ques_query,
        'id':ques_id,
        'quiz_id':quiz_id,
        'can_practice': True,
        'quiz_id': quiz_id,

    }
    return render(request, 'edit_question.html', context)

@login_required
def practice(request, user=None,*args, **kwargs):
    quiz_id = kwargs.get('quiz_id')
    quiz_filter = Quiz.objects.filter(quiz_id=quiz_id, user=user).prefetch_related()

    if request.POST:
        flip = request.POST.get('flip')
        test = request.POST.get('test')
        if test:
            context = {
                'quiz': quiz_filter.all(),
            }
            return render(request, 'practice_test.html', context)
        
        return HttpResponse('Feature Not yet implemeted')
    if quiz_filter.exists():
        context = {
            'quiz_id':quiz_id,
        }
        return render(request, 'practice.html', context)
    return redirect('/')

@login_required
def check_answer(request, user=None,*args):
    post_info = request.POST
    lst_template = []
    correct = []
    correct_len = 0
    wrong = []
    wrong_len = 0
    anss = ''
    if post_info:
        question = post_info.getlist('question')
        filters = Answers.objects.filter(ques_id__in = question).select_related().all()
        # loop over the question and check if the answer is correct
        for ques in question:
            for answer in filters:
                if answer.ans_correct:
                    anss = answer.ans
                    quiz_id=answer.quiz_id
                # get the answers for the current questions
                if answer.ques_id.ques_id == ques:
                    # get the answer you chose and check mif it's right and wrong
                    chosen_answer  = post_info.get(ques) 
                    if chosen_answer == answer.ans_id and answer.ans_correct:
                        context = {
                        'question':answer.ques_id.ques,
                        'correct':True,
                        'answer':anss,
                    }

studybud/studybud/templates/add_ques.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Add Question
{% endblock %}

{% block css %}
{% static 'add_ques.css' %}
{% endblock %}

{% block body %}
    <p id="error"></p>

    <form hx-encoding="multipart/form-data" hx-post="{% url 'add_questions' quiz_id=quiz_id%}" hx-trigger="submit", hx-target="#error" hx-swap="innerhtml" id="question_form">
    {% csrf_token %}
    <div id="question">
        {{image}} image
    {% if image %} <img src="{% static image %}" > {% endif %}
    {{question.question.label}}<br>
    {{question.question}}
    </div>
    <div id="answers">
    {{answer}}
    {{answer}}
    {{answer}}
    </div>
    
    <div id="correct_ans">
    {{correct}}
    </div>
    <br>
    <button type="submit">Submit</button>
    </form>


    <div id="otheroptions">
        <button hx-get="{% url 'get-form' what_form='ques'%}" hx-target="#question">Replace question one with text and image</button>
        <button hx-get="{% url 'get-form' what_form='text_ans'%}" hx-target="#answers" hx-swap="beforeend">Add Another Answer Feild</button>
        <button hx-get="{% url 'get-form' what_form='ans_with_image'%}" hx-target="#answers" hx-swap="beforeend">Image and text Answer </button>
        <button hx-get="{% url 'get-form' what_form='correct_ans'%}" hx-target="#correct_ans" hx-swap="innerhtml">Replace Text correct with correct Answer with Image and text</button>

        <button type="button" onclick="remove_last()">Remove last question input</button>
    </div>
    <script>
        function remove_last(){
            var answer_lst = document.getElementById('answers');
            if (answer_lst.lastChild.nodeName == '#text'){
            answer_lst.removeChild(answer_lst.lastChild)
            answer_lst.removeChild(answer_lst.lastChild)
            }
            else{
                answer_lst.removeChild(answer_lst.lastChild)
            }
        }
    </script>
    <h1> Questions </h1>
    (Questions with images will only display the text)
    <div id="questions" hx-swap-oob="true">
        {% for question in questions %}
        <div class="question" id="h{{question.ques_id}}">
            {{question.ques}}
            <button type="button" onclick="location.href='{% url 'edit_questions' ques_id=question.ques_id%}'">Edit Answers</button>
            <button type="button" hx-get="{% url 'delete' type='question' id=question.ques_id%}" hx-target="#h{{question.ques_id}}">Delete</button>
        </div>
        {% endfor %}
    </div>
{% endblock %}

studybud/studybud/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="{% static 'htmx.min.js' %}" defer></script>
    

    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% include 'navbar.html' %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" href="{% block css %}{% endblock %}">
    <link rel="stylesheet" href="{% block second_css %}{% endblock %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

studybud/studybud/templates/check.html
{{question}}

{% if correct %}
<!-- make the color a border -->

<p>
    You're Right:
    <span class="correct_answer">{{answer}}</span>
</p>
{% else %}
<br>

<!-- Change to use images to show wrong and right-->
<p>
    Your Answer:
    <span class="wrong_answer">{{chosen}}</span>
</p>


<p>
    Correct Answer:
    <span class="correct_answer">{{answer}}</span>
</p>

{% endif %}

studybud/studybud/templates/edit_question.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Edit Question
{% endblock %}

{% block css %} {% static 'add_ques.css' %}{% endblock %}


{% block body %}
<h1>Edit Question & Answers </h1>
<p id="error"></p>
<form hx-encoding="multipart/form-data" hx-post="{% url 'edit_questions' ques_id=id}" hx-trigger="submit", hx-target="#error" hx-swap="innerhtml" id="question_form">
{% csrf_token %}
{% for query in ques%}
<input type="text" name="ques_id" value="{{id}}" hidden>
<input type="text" name="quiz_id" value="{{quiz_id}}" hidden>
<!-- Question  -->
<div id="question">
    <div>
        <label for="id_question">Question :</label>
        <textarea name="question" cols="40" rows="2" placeholder="hello" required id="id_question">
            {{query.ques}}
        </textarea>
    </div>
    <div id="answer">
        {% for answer in query.answers_set.values%}

        
    {%  if answer.ans_correct%}
        {%  if answer.image is None%}
        <input type="text" name="correct_ans_id" value="{{answer.ans_id}}" hidden>
        <!-- Correct Answer -->
        <div id="correct_ans">
            <label for="id_correct_answer">Correct Answer:</label>
            <input type="text" name="correct_answer" required id="id_correct_answer" value="{{answer.ans}}">
            <button type="button" hx-get="{% url 'delete' type='answer' id=answer.ans_id%}" hx-target="#correct_ans">Delete</button>

        </div>
        {%  else %}
        <button type="button" hx-get="{% url 'delete' type='answer' id=answer.ans_id%}" hx-target="#h{{answer.ans_id}}">Delete Answer with image ( to add images just create a new question)</button>
        {% endif %}
    {% else %}
        {% if answer.image is None%}
            <input type="text" name="ids" value="{{answer.ans_id}}" hidden>
                    <!-- Answer -->
            <div id="h{{answer.ans_id}}">
                <label for="id_answer">Answer: </label>
                <input type="text" name="answer" required id="id_answer" value="{{answer.ans}}">
            <button type="button" hx-get="{% url 'delete' type='answer' id=answer.ans_id%}" hx-target="#h{{answer.ans_id}}">Delete</button>

            </div>
            {% else %}
            <button type="button" hx-get="{% url 'delete' type='answer' id=answer.ans_id%}" hx-target="#h{{answer.ans_id}}">Delete Answer with image ( to add images just create a new question)</button>
            {% endif %}
        {% endif %} 
    {% endfor %}
    </div>
    {% endfor %}
<button type="submit">Submit</button>

<div>
    <button hx-get="{% url 'get-form' what_form='text_ans'%}" hx-target="#answer" hx-swap="beforeend">Add Another Answer Feild</button>
</div>
{% endblock %}

studybud/studybud/templates/home.html
{% extends 'base.html' %}
{% load static%}

{% block title %}
HOME
{% endblock %}
{% block css %}
{% static 'homepage.css' %}
{% endblock %}

{% block body %}
<h2>Add Test</h2>
<form hx-post="{% url 'home' %}" hx-trigger="submit" hx-target="#edit_tests" hx-swap="beforeend">
{% csrf_token %}
{{quiz_form}}
<br>
<button type="submit">Submit</button>
</form>
    <h3>Current Tests</h3>
    <div id="edit_tests">
        {% for quiz in quizes %}
        <div id="h{{quiz.quiz_id}}" class="quiz_boxes">
            <h3 name="quiz_name">{{quiz.quiz_name}}</h3><br>
            <div class="options">
            <button type="button" onclick="location.href='{% url 'practice' quiz_id=quiz.quiz_id%}'">Practice/Learn Quiz</button>
            <button type="button" onclick="location.href='{% url 'add_questions' quiz_id=quiz.quiz_id%}'">Add or Edit Questions</button>
            
            <button type="button" onclick="location.href='{% url 'report' quiz_id=quiz.quiz_id%}'">Get Reports</button>
            
            <button type="button" hx-get="{% url 'delete' type='quiz' id=quiz.quiz_id%}" hx-target="#h{{quiz.quiz_id}}">Delete</button>
            </div>
        </div><br>
        
        {%  endfor %}
    </div>
{% endblock %}

studybud/studybud/templates/navbar.html
<nav>
    <ul><a href="{% url 'home' %}"> HOME </a></ul>
    {% if can_practice %}
    <ul><a href="{% url 'practice' quiz_id=quiz_id%}"> Practice Test </a> </ul>
    {% endif %}
    <ul> ABOUT </ul>
    <ul> CONTACT </ul>
</nav>

studybud/studybud/templates/practice.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Practice
{% endblock %}
{% block second_css %} {% static 'check.css' %}{% endblock %}
{% block css %}{% static 'practice.css' %}{% endblock %}
{% block body %}

<div class="choose">
<form hx-post="{% url 'practice' quiz_id=quiz_id%}" hx-target="#contents" hx-trigger="submit">
    {% csrf_token %}
    <input type="text" name="flip" value="Flip" hidden>
<button type="submit">Flip</button>
</form>
<br>
<form hx-post="{% url 'practice' quiz_id=quiz_id%}" hx-target="#contents" hx-trigger="submit">
    {% csrf_token %}
    <input type="text" name="test" value="test" hidden>
<button type="submit">Test form</button>
</form>
</div>
<br>
<br>
<div id="contents">

</div>


{% endblock %}

studybud/studybud/templates/practice_test.html
{% load template%}


<title> Practice </title>




<body>
<div>
    <form hx-post="{% url 'check' %}">
        {% csrf_token %}
    {% for obj in quiz %}
        {% if obj.questions_set.all%}
            
            {% for question in obj.questions_set.all %}
                <div class="ques_and_ans_box">
                    {{forloop.counter}}.
                    <input type="text" name="question" value="{{question.ques_id}}" hidden>{{question.ques}}</input></br></br>
                    
                    {% if question.ques_image %}
                    <img src="/{{question.ques_image }}" alt="Question Image" width="200px" height="200px" defer>
                    <br>
                    <br>
                    {% endif %}
                    <div class="ans">
                {% for answer in obj|get_filter:question.ques_id %}
                    {% if answer.ans_image %}
                        <div>
                        <input type="radio" name="{{question.ques_id}}" value="{{answer.ans_id}}" id="h{{answer.ans_id}}">
                        <img src="/{{answer.ans_image}}" alt="answer image" width="150px" height="150px" defer>
                        <label for="h{{answer.ans_id}}">{{answer.ans}}</label>
                        </div>
                    {% else %}
                    <div>
                        <input type="radio" name="{{question.ques_id}}" value="{{answer.ans_id}}" id="h{{answer.ans_id}}">
                        <label for="h{{answer.ans_id}}">{{answer.ans}}</label>
                        </div>
                    {% endif %}
                {% endfor %}
                </div>
                </div>

        </br>
            {% endfor %}
            <button type="submit">Submit</button>
        {% else %}
            <p>No Questions add questions at <button type="button"> <a href="{% url 'add_questions' quiz_id=obj.quiz_id%}">Add or Edit Questions</a></button></p>
        {% endif %}

    {% endfor %}
    </form>
</div>
</body>

studybud/studybud/templates/question.html
<div hx-swap-oob="beforeend:#questions" >
    <div class="question" id="h{{ques_id}}">
        {{quess}} <button type="button" onclick="location.href='{% url 'edit_questions' ques_id=ques_id%}'">Edit Answers</a></button>
        <button type="button" hx-get="{% url 'delete' type='question' id=ques_id%}" hx-target="#h{{ques_id}}">Delete</button>
    </div>
</div>
<script>
    document.getElementById('question_form').reset()
</script>

studybud/studybud/templates/report.html
{% extends 'base.html' %}
{% load template %}
{% load static %}
{% block title %}
Report
{% endblock %}


{% block css %}{% static 'report.css' %}{% endblock %}

{% block body %}
<script>
function replace(id) {
    document.getElementById('display').innerHTML = document.getElementById(id).innerHTML
}
</script>


Atempts: {{reports|length}}
<div class="attempt">
{% for attempt in reports %}
    Attempt {{forloop.counter}}<br>
    Score : {{attempt.score}}
    <button type="submit" value="h{{forloop.counter}}" onclick="replace('h{{forloop.counter}}')">Show Results</button>
    {% for report in reports %}
    <div id="h{{forloop.counter}}" hidden defer>
    <h3>Attempt {{ forloop.counter }}</h3>
    {{report|check_html}}
        <br>
        <br>
    </div>
        {% endfor %}
    {% endfor %}
</div> 


<div id="display">

</div>

{% endblock %}

studybud/studybud/templates/results.html
{% load static %}
<title>
Result
</title>

<link rel="stylesheet" href="{% static 'check.css' %}">

<body>
{% if correct_ans%}
    <p>Score : {{correct_ans}}/{{total}}</p>
{% endif %}
<div id="content">

{% for template in lst_template %}
{{forloop.counter}}. {{template}}

{% endfor %}
</div>


</body>

studybud/studybud/templates/test_created.html
<div id="h{{quiz_id}}" class="quiz_boxes">
    <h3 name="quiz_name">{{quiz_name}}</h3>
    
    {{quiz.quiz_name}}
    <button type="button" onclick="location.href='{% url 'practice' quiz_id=quiz_id%}'">Practice/Learn Quiz</button>
    <button type="button" onclick="location.href='{% url 'add_questions' quiz_id=quiz_id%}'">Add or Edit Questions</button>
    
    <button type="button" onclick="location.href='{% url 'report' quiz_id=quiz_id%}'">Get Reports</button>
    
    <button type="button" hx-get="{% url 'delete' type='quiz' id=quiz_id%}" hx-target="#h{{quiz_id}}">Delete</button>


</div><br>

<script>
    document.getElementById('id_quiz_name').value = ''
</script>